config/routes.rb
Rails.application.routes.draw do

  root 'cv_pages#home'
  get '/cv', to: 'cv_pages#show'
  get '/about', to: 'cv_pages#about'
  get '/portfolio', to:'cv_pages#portfolio'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cv_pages_controller.rb
class CvPagesController < ApplicationController
  def show
  end

  def home
  end

  def about
  end

  def portfolio
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cv_pages_helper.rb
module CvPagesHelper
end

app/views/cv_pages/_header.html.erb
<div class='nav'>
  <%=link_to 'Qianyao HAO', root_path, class:'logo' %>
  <ul>
    <li><%=link_to 'HOME', root_path %></li>
    <li><%=link_to 'ABOUT', about_path %></li>
    <li><%=link_to 'RESUME', cv_path %></li>
    <li><%=link_to 'PORTFOLIO', portfolio_path %></li>
  </ul>
</div>

app/views/cv_pages/about.html.erb
<%=render 'header' %>
<div class='about'>
  <h2>Hi, I'm Yao </h2>
  <p class='paragraph'> I moved to France from China about 5 years ago to pursue
      my Master's degree in Finance. Upon graduation, I worked for 2 years as a financial
      controller, first at French multinational Schneider Electric, then at American e-commerce giant Amazon.
      Both experiences were precious but I gradually discovered that Finance is not really
      my passion, and my work became just a way of earning money.</p>

  <p class='paragraph'> I first discovered programming at Amazon and really enjoyed it.
      With the encouragement of my husband, I started to do some simple courses
      on CodeAcademy. Time always passed more quickly when I was programming and I wanted
      to be able to do more and more. But with the workload at Amazon, it soon became
      complicated. So I addressed my intention to change my career to my boss and at the
      beginning of 2017, I left my job to start a new adventure.</p>

  <p class='paragraph'> I started teaching myself Rails full time with all the
      great resources on the Internet. After a month of learning and building a
      small CMS system, I started on BATMAP, an idea I had while finding public
      ping-pong tables to play on around our home.</p>

  <p class='paragraph'> Now I'm hoping to use the knowledge I've taught myself to
      start a new chapter of my career. </p>
</div>

app/views/cv_pages/home.html.erb
<div class='home'>
  <div class='title'>
    <h1>RUBY ON RAILS DEVELOPER</h1>
    <ul>
      <li><%=link_to 'HOME', root_path %></li>
      <li><%=link_to 'ABOUT', about_path %></li>
      <li><%=link_to 'RESUME', cv_path %></li>
      <li><%=link_to 'PORTFOLIO', portfolio_path %></li>
    </ul>
  </div>
</div>

app/views/cv_pages/portfolio.html.erb
<%=render 'header' %>
<div class='portfolio'>
  <div class='project'>
    <div class='project_picture'>
      <%=link_to 'https://batmap.herokuapp.com/', class:'picture_link' do %>
        <%=image_tag('Batmap', width: 600, class:'picture')%>
        <%=image_tag('Batmap2', width: 600, class:'picture')%>
      <% end %>
    </div>
    <div class='project_description'>
      <h1><%=link_to 'Batmap','https://batmap.herokuapp.com/'%> </h1>
      <p>An app that I built after 1 month learning of rails. This app finds nearby public pingpong tables. User can also rate/like a table and arrange match on it</p>
      <h3>Features</h3>
      <ul>
        <li><strong>User Authentication:</strong> authentication system from scratch, with account activation, password reset etc </li>
        <li><strong>Google maps API:</strong> user geolocation, location search auto complete, search by bound change(zoom, drag), responsive marker/info window</li>
        <li><strong>Action Cable and Websocket: </strong>instant messaging, mailbox unread auto update and notifications with Action Cable </li>
        <li><strong>Full calendar:</strong> JS full calendar library for match arranging, event data handling using jbuilder</li>
        <li><strong>ActiveJob:</strong> use ActiveJob to handle background jobs like creating notifications and broadcast through websocket channels</li>
        <li><strong>Photo upload:</strong> use Carrierwave and jQuery-File-Upload gem for multiple photo uploads. Fog and Amazon S3 for production </li>
        <li><strong>Comments:</strong> use nested form and self-join form for implementation of forum like comments/replies</li>
        <li><strong>Testing: </strong> model and integration test with Rspec, Capybara, Selenium, FactoryGirl (added testing after project as when I was building the project, I hadn't learnt Rspec)</li>
        <li><strong>View cleaning: </strong> a taste of 'presenter' for 'conversation' index view </li>
      </ul>
    </div>
  </div>
  <div class='project'>
    <div class='project_picture'>
      <%=link_to 'https://yaofund.herokuapp.com/', class:'picture_link' do %>
        <%=image_tag('fund', width: 600, class:'picture')%>
      <% end %>
    </div>
    <div class='project_description'>
      <h1><%=link_to 'Yaofund','https://yaofund.herokuapp.com/'%> </h1>
      <p>A fundraising site for mental illness</p>
      <h3>Features</h3>
      <ul>
        <li><strong>User Authentication:</strong> use Devise for authentication system and Omniauth for social network login</li>
        <li><strong>Bootstrap:</strong> use Bootstrap for whole site styling</li>
        <li><strong>Background Jobs: </strong> use Sidekiq for alert emails</li>
        <li><strong>Fulltext search: </strong> use PostgreSQL full text search with pg_search</li>
      </ul>
    </div>
  </div>
</div>

app/views/cv_pages/show.html.erb
<%=render 'header' %>
<div class='cv'>
  <header>
    <h1 class="name">Qianyao HAO</h1>Back-end developer
    <div class="intro">Self-taught Ruby on Rails developer from a finance background, looking for a chance to gain work experience with Ruby on Rails. Willing to work hard and excited to continue learning new skills</div>
  </header>
  <section class="mainSection skills">
    <h2>Key skills<i class="fa fa-wrench fa-rotate-270"></i></h2>
    <ul class="skills_list">
      <li class="skill">
        <h3 class="skill_title">Languages</h3>
        <ul class="skill_details">
          <li class="skill_detail">Ruby</li>
          <li class="skill_detail">SQL</li>
          <li class="skill_detail">Coffeescript</li>
          <li class="skill_detail">Javascript (Jquery, Ajax)</li>
          <li class="skill_detail">HTML5</li>
          <li class="skill_detail">CSS3 (Sass, Bootstrap)</li>
          <li class="skill_detail">VBA</li>
        </ul>
      </li>
      <li class="skill">
        <h3 class="skill_title">Database</h3>
        <ul class="skill_details">
          <li class="skill_detail">PostgreSQL</li>
          <li class="skill_detail">MySQL</li>
          <li class="skill_detail">SQLite</li>
          <li class="skill_detail">Oracle</li>
        </ul>
      </li>
      <li class="skill">
        <h3 class="skill_title">Deployment Tools</h3>
        <ul class="skill_details">
          <li class="skill_detail">Heroku</li>
          <li class="skill_detail">Git</li>
          <li class="skill_detail">Amazon S3</li>
        </ul>
      </li>
      <li class="skill">
        <h3 class="skill_title">Testing Tools</h3>
        <ul class="skill_details">
          <li class="skill_detail">Rspec</li>
          <li class="skill_detail">FactoryGirl</li>
          <li class="skill_detail">Capybara</li>
          <li class="skill_detail">Selenium</li>
        </ul>
      </li>
      <li class="skill">
        <h3 class="skill_title">Strong knowledge in MVC framework architecture, CRUD operations and REST architecture</h3>
      </li>
      <li class="skill">
        <h3 class="skill_title">Experience in database modeling and design</h3>
      </li>
      <li class="skill">
        <h3 class="skill_title">Good understanding of Action Cable and WebSocket</h3>
      </li>
      <li class="skill">
        <h3 class="skill_title">Good understanding of background jobs using ActiveJob and Sidekiq</h3>
      </li>
      <li class="skill">
        <h3 class="skill_title">Good understanding of OOP Concepts</h3>
      </li>

    </ul>
  </section>
  <section class="mainSection">
    <h2>Experience<i class="fa fa-briefcase" aria-hidden="true"></i></h2>
    <ul>
      <li class="experienceEntry">
        <h3> <span class="experienceEntry_dates">June 2016 - December 2016</span><span class="experienceEntry_title">Business Analyst</span><span class="experienceEntry_company">Amazon Logistics</span><span class="experienceEntry_where">Sevrey, France</span></h3>
        <ul class="experienceEntry_list">
          <li>Daily productivity and performance analysis</li>
          <ul class="experienceEntry_sublist">
            <li>Using SQL and VBA to consolidate and analyse huge sets of data on warehouse's everyday productivity</li>
            <li>Monitor and publish daily/weekly/monthly performance indicators</li>
            <li>Explain the data-based analysis to operations and suggest improvement plans</li>
          </ul>
          <li>Involved in implementation of new coaching project by providing huge data analysis using complex SQL queries</li>
          <li>Implemented new budget controlling tool using VBA and SQL </li>
        </ul>
      </li>
    </ul>
    <ul>
      <li class="experienceEntry">
        <h3> <span class="experienceEntry_dates">June 2014 - June 2016</span><span class="experienceEntry_title">Financial Controller</span><span class="experienceEntry_company">Schneider Electric</span><span class="experienceEntry_where">Rueil-Malmaison, France</span></h3>
        <ul class="experienceEntry_list">
          <li>Leader on Prior project, Partner Business Unit's only point of contact with all countries and Corporate to ensure an accurate financial baseline</li>
          <li>Led the transition of Partner Business Unit (€12bn turnover) and put in place the whole financial reporting process</li>
        </ul>
      </li>
    </ul>
  </section>
  <section class="mainSection">
    <h2>Education<i class="fa fa-mortar-board"></i></h2>
    <ul>
      <li class="experienceEntry">
        <h3><span class="experienceEntry_dates">January 2017 - Present</span><span class="experienceEntry_title">Self-teaching Programming</span><span class="experienceEntry_home">Code Academy, Lynda, Rails documentation, Railscast, Rails Tutorial ... </span></h3>
      </li>
      <li class="experienceEntry">
        <h3><span class="experienceEntry_dates">September 2012 - June 2014</span><span class="experienceEntry_title">Corporate and market finance (Master 2)</span><span class="experienceEntry_company">IAE Grenoble</span><span class="experienceEntry_where">Grenoble, France</span></h3>
      </li>
      <li class="experienceEntry">
        <h3><span class="experienceEntry_dates">September 2009 - July 2013</span><span class="experienceEntry_title">French language and literature (BA)</span><span class="experienceEntry_company">Shanghai International Studies University</span><span class="experienceEntry_where">Shanghai, China</span></h3>
      </li>
    </ul>
  </section>
  <section class="mainSection">
    <h2>Other<i class="fa fa-coffee" aria-hidden="true"></i></h2>
    <ul class="skills_list">
      <li class="skill">
        <h3 class='skill_title'>Languages</h3>
        <ul class="skill_details">
          <li class="skill_detail">Chinese: native</li>
          <li class="skill_detail">English: bilingual</li>
          <li class="skill_detail">French: fluent</li>
        </ul>
      </li>
      <li class="skill">
        <h3 class='skill_title'>Interests</h3>
        <ul class="skill_details">
          <li class="skill_detail">Travel</li>
          <li class="skill_detail">Piano</li>
          <li class="skill_detail">Film</li>
          <li class="skill_detail">Psychology</li>
        </ul>
      </li>
    </ul>
  </section>
  <section class="contact" id="contact">
    <div><a class="contact_link" href="mailto:Qianyaohao91@gmail.com"><i class="fa fa-envelope contact_icon"></i><span class="contact_link_content">Qianyaohao91@gmail.com</span></a></div>
    <div><a class="contact_link" href="tel:+33622744105"><i class="fa fa-phone contact_icon"></i><span class="contact_link_content">+33 (0) 6 22 74 41 05 </span></a></div>
    <div><a class='contact_link' href="https://bitbucket.org/Rosalie123/"><i class="fa fa-bitbucket contact_icon" aria-hidden="true"></i><span class="contact_link_content">bitbucket.org/Rosalie123</span></a></div>
    <div class="contact_address"> <i class="fa fa-home contact_icon contact_address_icon"></i><span>11 rue Victor Lacaille d'Esse,<br/>
        71100 Chalon-sur-Saône, France</span></div>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cv</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,600" rel="stylesheet">
    <script src="https://use.fontawesome.com/19b9ba9e08.js"></script>
    <meta name="robots" content="noindex, nofollow" />
  </head>

  <body>
    <%= yield %>
  </body>
</html>